#!/bin/bash

# Simple script to copy the files to a project

set -e

if [ "$#" -ne 1 ]; then
    echo "You need to supply a path..."
    echo
    echo "copyto ~/code/some-project-name/"
    exit 1
fi

cp -av docker .dockerignore .env.gitlab .gitlab-ci.yml Dockerfile prod-stack.yml qa-stack.yml docker-compose.yml LICENSE "$1"
