version: "2.4"

# See https://github.com/UoGSoE/docker-stuff for the origins of this file

services:
  phpunit:
    build:
      context: .
      dockerfile: phpunit.Dockerfile
      args:
        PHP_VERSION: 7.3
    depends_on:
      mysql:
        condition: service_healthy
    tmpfs:
      - /var/www/html/storage/logs
      - /var/www/html/storage/framework/cache
    environment:
     DB_CONNECTION: mysql
     DB_HOST: mysql
     DB_DATABASE: homestead
     DB_USERNAME: homestead
     DB_PASSWORD: secret
    volumes:
      - .:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    healthcheck:
      test: /usr/bin/mysql --host=127.0.0.1 --user=homestead --password=secret --silent --execute \"SELECT 1;\"
      interval: 3s
      timeout: 20s
      retries: 5

