#!/usr/bin/env bash

set -eo pipefail

role=${CONTAINER_ROLE:-app}

if [ "$role" = "app" ]; then

    curl -f http://localhost/login || exit 1
    exit 0

elif [ "$role" = "queue" ]; then

    ps -fe | egrep -q '[h]orizon' || exit 1
    exit 0

elif [ "$role" = "scheduler" ]; then

    # need to figure something out for this... if at all checkable
    exit 0

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
