#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

if [ "${env}" != "production" ];
then
    # in QA/testing we wait for the local mysql container to come up
    until nc -z -v -w30 mysql 3306
    do
        echo "Waiting for database connection..."
        sleep 5
    done
fi

until echo 'PING' | nc -w 1 redis 6379 | grep -q PONG
do
    echo "Waiting for Redis connection..."
    sleep 5
done

php /var/www/html/artisan config:cache

if [ "$role" = "app" ]; then

    exec apache2-foreground

elif [ "$role" = "queue" ]; then

    trap "gosu www-data php /var/www/html/artisan horizon:terminate" SIGTERM
    exec gosu www-data nice php /var/www/html/artisan horizon

elif [ "$role" = "scheduler" ]; then

    exec gosu www-data nice php /var/www/html/artisan schedule:work --verbose --no-interaction
#    while [ true ]
#    do
#      gosu www-data nice php /var/www/html/artisan schedule:run --verbose --no-interaction &
#      sleep 60
#    done

elif [ "$role" = "migrations" ]; then

    gosu www-data php /var/www/html/artisan migrate --force
    while [ true ]
    do
        sleep 86400
    done

elif [ "$role" = "test" ]; then

    exec gosu www-data php /var/www/html/vendor/bin/phpunit --colors=never

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
